apiVersion: v1
kind: Service
metadata:
  name: binarycalc-service
spec:
  selector:
    app: BinaryCalculatorWebapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
