apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-calculator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: binary-calculator
  template:
    metadata:
      labels:
        app: binary-calculator
    spec:
      containers:
        - name: binary-calculator
          image: gcr.io/YOUR-PROJECT-ID/binary-calculator:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
