apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BinaryCalculatorWebapp
  template:
    metadata:
      labels:
        app: BinaryCalculatorWebapp
    spec:
      containers:
      - image: northamerica-northeast2-docker.pkg.dev/complete-aviary-452402-m3/sofe3980u/binwebappv2
        name: binwebappv2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
